import { PERMISSIONS } from "./permissions.js";
import { ROLES } from "./roles.js";

export const ROLE_PERMISSIONS: Record<string, string[]> = {
    [ROLES.ADMIN]: Object.values(PERMISSIONS),

    [ROLES.MANAGER]: [
        PERMISSIONS.COURSE_CREATE,
        PERMISSIONS.COURSE_READ,
        PERMISSIONS.COURSE_UPDATE,
        PERMISSIONS.COURSE_MANAGE,

        PERMISSIONS.PAYMENT_VIEW,
        PERMISSIONS.PAYMENT_HISTORY,

        PERMISSIONS.USER_READ,
    ],

    [ROLES.INSTRUCTOR]: [
        PERMISSIONS.COURSE_CREATE,
        PERMISSIONS.COURSE_READ,
        PERMISSIONS.COURSE_UPDATE,

        PERMISSIONS.STUDENT_READ,
    ],

    [ROLES.SUPPORT]: [
        PERMISSIONS.COURSE_READ,
        PERMISSIONS.STUDENT_READ,
        PERMISSIONS.STUDENT_SUPPORT,
    ],

    [ROLES.STUDENT]: [
        PERMISSIONS.COURSE_READ,
        PERMISSIONS.COURSE_ENROLL,
        PERMISSIONS.SELF_READ,
        PERMISSIONS.SELF_UPDATE,
        PERMISSIONS.SELF_DELETE,
    ],
};
export type RolePermissions = typeof ROLE_PERMISSIONS;