import type { NextFunction, Request, Response } from "express";
import mongoose from "mongoose";
import _config from "src/configs/_config.js";
import logger from "src/helpers/logger.js";
import { ApiError } from "src/utils/apiError.js";
import { ZodError } from "zod";



//Generated by ChatGPT not me
interface IErrorResponse {
    statusCode: number;
    message: string;
    errors?: Array<{ path?: string; message: string }>;
    stack?: string;
}

const globalErrorHandler = (
    err: unknown,
    req: Request,
    res: Response,
    _next: NextFunction
): void => {
    let errorResponse: IErrorResponse = {
        statusCode: 500,
        message: "Internal Server Error"
    };

    // 🔍 ZOD Validation Error
    if (err instanceof ZodError) {
        errorResponse = {
            statusCode: 400,
            message: "Validation failed",
            errors: err.issues.map(issue => ({
                path: issue.path.join("."),
                message: issue.message
            }))
        };
    }

    // 🎯 Mongoose Duplicate Key Error
    else if (
        typeof err === "object" &&
        err !== null &&
        "code" in err &&
        err.code === 11000
    ) {
        const dup = err as any;
        const keyValue = dup.keyValue || {};

        errorResponse = {
            statusCode: 400,
            message: "Duplicate value",
            errors: Object.keys(keyValue).map(key => ({
                path: key,
                message: `${key} must be unique`
            }))
        };
    }

    // 🧠 Mongoose Cast Error (Invalid ObjectId)
    else if (err instanceof mongoose.Error.CastError) {
        errorResponse = {
            statusCode: 400,
            message: "Invalid ID format",
            errors: [
                {
                    path: err.path,
                    message: `Invalid value '${err.value}' for field '${err.path}'`
                }
            ]
        };
    }

    // 📦 Mongoose Validation Error
    else if (err instanceof mongoose.Error.ValidationError) {
        errorResponse = {
            statusCode: 400,
            message: "Validation failed",
            errors: Object.values(err.errors).map((e: any) => ({
                path: e.path,
                message: e.message
            }))
        };
    }

    // 🎯 Custom API Error
    else if (err instanceof ApiError) {
        errorResponse = {
            statusCode: err.statusCode,
            message: err.message,
            errors: err.errors,
            stack: err.stack
        };
    }

    // 🐞 Native JS Error
    else if (err instanceof Error) {
        errorResponse = {
            statusCode: 500,
            message: err.message,
            stack: err.stack
        };
    }

    // ❓ Unknown Error Object / External lib throw
    else {
        logger.error("Unknown Error Type", { err });
    }

    // 📊 Structured Logging once — clean & clear
    logger.error("API Error", {
        method: req.method,
        url: req.originalUrl,
        ip: req.ip,
        statusCode: errorResponse.statusCode,
        message: errorResponse.message,
        errors: errorResponse.errors,
        stack: errorResponse.stack
    });

    // 🛑 Final Response
    const responseBody: any = {
        success: false,
        message: errorResponse.message,
        statusCode: errorResponse.statusCode
    };

    if (errorResponse.errors) responseBody.errors = errorResponse.errors;

    if (_config.NODE_ENV !== "production" && errorResponse.stack) {
        responseBody.stack = errorResponse.stack;
    }

    res.status(errorResponse.statusCode).json(responseBody);
};

export default globalErrorHandler;
